3 cups carrot(450 g), hand-grated

2 ½ cups all-purpose flour(310 g), plus 1 tablespoon, divided

2 teaspoons ground cinnamon

¼ teaspoon allspice

1 teaspoon kosher salt

1 teaspoon baking powder

½ teaspoon baking soda

1 cup light brown sugar(200 g), packed

½ cup granulated sugar(100 g)

3 large eggs, room temperature

1 cup vegetable oil(240 mL)

1 cup raisin(150 g)

1 cup crushed pineapple(225 g), canned